# Generated by Django 3.2.14 on 2022-07-30 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Name of model"),
                ),
                ("description", models.TextField(verbose_name="Description of model")),
                ("address", models.TextField(verbose_name="Address/link of event")),
                (
                    "datetime_spending",
                    models.DateTimeField(verbose_name="Event's time spending"),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="Is online event"),
                ),
                (
                    "is_open",
                    models.BooleanField(default=True, verbose_name="Is open field"),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="events_member",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Members of event",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner of event",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
