exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--settings-file=./server/setup.cfg"]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--config=./server/setup.cfg"]
        additional_dependencies: [flake8-isort]
